/**
 * exporters/clientSummary.js — a formatted, human-facing quote sheet.
 *
 * Different audience from the TSV: this one goes in an email to a client, so
 * it is plain text with no machine columns, no missing-field diagnostics, and
 * an explicit note about what is not shown.
 */

import { resolveSupplier, formatPrice, isManufacturer } from '../compare.js';

const RULE = '='.repeat(66);
const THIN = '-'.repeat(66);

const yesNo = (b) => (b === true ? 'Yes' : b === false ? 'No' : '');

export const clientSummary = {
  id: 'clientSummary',
  label: 'Copy quote summary',
  description: 'Formatted plain text for sending to a client or your team.',
  mime: 'text/plain',
  extension: 'txt',
  build(records, settings = {}) {
    const qty = settings.targetQty ?? 1;
    const out = [];
    const now = new Date().toISOString().slice(0, 10);

    out.push(RULE);
    out.push('SUPPLIER COMPARISON SUMMARY');
    out.push(`Quantity requested: ${qty}`);
    out.push(`Prepared: ${now}`);
    out.push(RULE);
    out.push('');

    if (!records.length) {
      out.push('No suppliers have been added yet.');
      return out.join('\n');
    }

    const resolved = records.map((r) => resolveSupplier(r, qty));

    // Group by currency so the sheet never implies a cross-currency ranking.
    const groups = new Map();
    for (const c of resolved) {
      if (!c.ok) continue;
      const cur = c.currency || 'USD';
      if (!groups.has(cur)) groups.set(cur, []);
      groups.get(cur).push(c);
    }

    if (groups.size > 1) {
      out.push('NOTE: Suppliers quote in more than one currency. Groups below are NOT');
      out.push('       compared to each other. Convert before deciding.');
      out.push('');
    }

    let n = 0;
    for (const [currency, rows] of groups) {
      const sorted = rows.slice().sort((a, b) => a.unitPrice - b.unitPrice);
      out.push(`--- QUOTED IN ${currency} ` + '-'.repeat(Math.max(0, 50 - currency.length)));
      out.push('');
      for (const c of sorted) {
        n++;
        const r = c.record;
        out.push(`${n}. ${r.companyName || 'Supplier (name not published)'}`);
        if (r.country) out.push(`   Country       : ${r.country}`);
        if (r.businessType) {
          out.push(`   Type          : ${r.businessType}${isManufacturer(r.businessType) ? '  [factory]' : ''}`);
        }
        out.push(`   Unit price    : ${formatPrice(c.unitPrice, currency)}`);
        if (Number.isFinite(Number(r.priceTo)) && Number(r.priceTo) > c.unitPrice) {
          out.push(`   Price range  : ${formatPrice(c.unitPrice, currency)} – ${formatPrice(r.priceTo, currency)}`);
        }
        if (Array.isArray(r.products) && r.products.length > 1) {
          out.push(`   Also lists   : ${r.products.length - 1} other product${r.products.length - 2 === 1 ? '' : 's'}`);
        }
        if (c.belowMoq) {
          out.push(`   Note          : quantity of ${qty} is below this supplier's minimum`);
          out.push(`                   order of ${r.moqQty}${r.moqUnit ? ' ' + r.moqUnit : ''}.`);
          out.push(`                   At their minimum (${c.orderQty}) the unit price is`);
          out.push(`                   ${formatPrice(c.unitPriceAtMoq, currency)}.`);
        } else {
          out.push(`   Order value   : ${formatPrice(c.total, currency)} at ${c.orderQty} units`);
        }
        const trust = [];
        if (r.verifiedSupplier) trust.push('Verified supplier');
        if (r.tradeAssurance) trust.push('Trade Assurance');
        if (Number.isFinite(r.yearsOnPlatform)) trust.push(`${r.yearsOnPlatform} yrs on platform`);
        if (r.responseRate) trust.push(`${r.responseRate} response rate`);
        if (r.leadTime) trust.push(`lead time ${r.leadTime}`);
        out.push(`   Credentials   : ${trust.length ? trust.join(' · ') : 'none published on the product page'}`);
        if (r.priceTiers.length > 1) {
          out.push(`   Volume pricing: ${r.priceTiers
            .map((t) => `${t.minQty}${t.maxQty ? '-' + t.maxQty : '+'} @ ${formatPrice(t.unitPrice)}`)
            .join('  ')}`);
        }
        if (r.sourceUrl) out.push(`   Product page  : ${r.sourceUrl}`);
        if (r.companyUrl) out.push(`   Company page  : ${r.companyUrl}`);
        out.push('');
      }
    }

    out.push(THIN);
    out.push('Notes');
    out.push('- Prices are the list prices published on each Alibaba product page at the');
    out.push('  time of capture. They exclude shipping, insurance, duties and any');
    out.push('  tooling or sample charges.');
    out.push('- Factory certification documents, audit reports and trade assurance cover');
    out.push('  limits are not published on the product page and must be requested from');
    out.push('  the supplier directly.');
    out.push('- Quantities below a supplier minimum order cannot be ordered from them.');
    out.push('');
    out.push('Generated by Alibaba Supplier Compare. Data read from pages you visited;');
    out.push('nothing was collected in the background and nothing left your computer.');
    out.push(THIN);

    return out.join('\n');
  },
};
